### ISSUE TITLE
Перепройти тесты

### ISSUE THREAD

**Issue by FlashAnton** [Komisar1/Programming#12]
Здравствуйте!

За сегодняшний день, с 12:00 до 16:00 необходимо перепройти следующие тесты:

1. https://docs.google.com/forms/d/e/1FAIpQLSe-zMPzGJRZriPA0qhGk7epJy4C9YWEpx-kI42pwKcVG2OWXA/viewform?usp=sf_link
2. https://docs.google.com/forms/d/e/1FAIpQLSc5dNumKVjiDyOYczUnAieerJWc2dIJs-kEBOsp_4PfSHb7bg/viewform?usp=sf_link
3. https://docs.google.com/forms/d/e/1FAIpQLScBAMcLqz2Aung9kj934-3CAeFAhtJDvHETVRTnF4n3gbXd6Q/viewform?usp=sf_link

**Comment by Komisar1** [comment]
Извините что поздно, сайт не грузил 
--
Отправлено из Mail.ru для Android среда, 27 декабря 2023г., 11:34 +03:00 от Anton Safronov  ***@***.*** :

**Comment by FlashAnton** [comment]
**Ни одно тестирование не пройдено.**

Для допуска к экзамену, помимо демонстрации комплекта выполненных работ, потребуется пройти итоговое тестирование, включающее вопросы по всем темам.
