### ISSUE TITLE
Замечания к работе №2

### ISSUE THREAD

**Issue by Komisar1** [Komisar1/Programming#3]
![test.docx](https://github.com/Komisar1/Programming/files/13167873/test.docx)

**Comment by FlashAnton** [comment]
Здравствуйте, @Komisar1 !

Прикреплять файлы нужно не в Issues.
Issues для обсуждения вопросов по работам и
вопросов по наполнению отчётной документации.

Файлы прикрепляются в Code.
![image](https://github.com/Komisar1/Programming/assets/95698986/7bae2766-4b54-4b25-87ac-77c7ea6e9530)

Фалы сбрасываются в обрамлённую область и обязательно делается Commit changes.
Текст заголовка коммита обязателен.
![image](https://github.com/Komisar1/Programming/assets/95698986/80c8da54-83d2-4b92-aae8-d0827b958af7)

**Comment by FlashAnton** [comment]
Здравствуйте.

Вижу Вашу программу по задаче №2 в репозитории.
Не вижу отчёта по этой задаче, приложенного к этой программе.
Что мне проверять?

**Comment by FlashAnton** [comment]
Теперь всё на месте.
У меня нет замечаний по выполнению Вами работы.

**Работа допущена к защите**

**Comment by FlashAnton** [comment]
**Работа защищена 29.11.2023 во время аудиторного занятия**
